# Generated by Django 5.2.10 on 2026-01-30 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderHeaders',
            fields=[
                ('po_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(max_length=50)),
                ('order_date', models.DateField(null=True)),
                ('expiry_date', models.DateField(null=True)),
                ('overall_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('asin', models.CharField(max_length=100)),
                ('sap_code', models.CharField(max_length=100)),
                ('sap_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=20)),
                ('requested_qty', models.FloatField(default=0)),
                ('accepted_qty', models.FloatField(default=0)),
                ('received_qty', models.FloatField(default=0)),
                ('cancelled_qty', models.FloatField(default=0)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_requested_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_accepted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_received_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cancelled_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fulfillment_center', models.CharField(max_length=100)),
                ('availability_status', models.CharField(max_length=100)),
                ('item_status', models.CharField(max_length=50)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Amazon.purchaseorderheaders')),
            ],
        ),
        migrations.CreateModel(
            name='SKUMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('dealshare', 'DealShare'), ('citymall', 'CityMall'), ('blinkit', 'Blinkit'), ('swiggy', 'Swiggy'), ('zepto', 'Zepto')], db_index=True, default='zepto', max_length=20)),
                ('external_sku_code', models.CharField(db_index=True, max_length=100)),
                ('sap_code', models.CharField(max_length=100)),
                ('sap_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('case_pack', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('uom', models.CharField(default='PCS', max_length=10)),
            ],
            options={
                'unique_together': {('platform', 'external_sku_code')},
            },
        ),
    ]
