# Generated by Django 5.2.10 on 2026-01-30 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amazon', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SKUMapping',
        ),
    ]
