# Generated by Django 5.2.10 on 2026-01-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SKUMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('dealshare', 'DealShare'), ('citymall', 'CityMall'), ('blinkit', 'Blinkit'), ('swiggy', 'Swiggy'), ('zepto', 'Zepto')], db_index=True, default='zepto', max_length=20)),
                ('external_sku_code', models.CharField(db_index=True, max_length=100)),
                ('sap_code', models.CharField(max_length=100)),
                ('sap_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('sub_category', models.CharField(blank=True, max_length=50, null=True)),
                ('case_pack', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('uom', models.CharField(default='PCS', max_length=10)),
            ],
            options={
                'unique_together': {('platform', 'external_sku_code')},
            },
        ),
    ]
