# Generated by Django 5.2.10 on 2026-01-30 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('dealshare', 'DealShare'), ('cityMall', 'CityMall'), ('Blinkit', 'Blinkit'), ('Swiggy', 'Swiggy'), ('Zepto', 'Zepto')], max_length=20)),
                ('po_number', models.CharField(max_length=100)),
                ('po_date', models.DateField()),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='CREATED', max_length=20)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_gstin', models.CharField(blank=True, max_length=20, null=True)),
                ('ship_to_address', models.TextField()),
                ('bill_to_address', models.TextField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('raw_file', models.FileField(blank=True, null=True, upload_to='po_raw/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('platform', 'po_number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_code', models.CharField(max_length=100)),
                ('vendor_sku', models.CharField(blank=True, max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('gst_percent', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.IntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buying_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Platforms.purchaseorder')),
            ],
        ),
    ]
